version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - sqli_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sqli_lab
    command: --secure-file-priv="" --sql-mode=""
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - sqli_network

  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8081:80"
    networks:
      - sqli_network

networks:
  sqli_network:
    driver: bridge
